// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: recording/v1/recording.proto

package recordingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommitRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // UUID v7 — must match SPIFFE cert
	CallId   string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`       // UUID v7 — FK to calls(id)
	// S3 layout (single bucket, paths derived):
	//
	//	audio_object_key = recordings/<tenant_id>/<yyyy>/<mm>/<dd>/<call_id>.opus.enc
	//	dek_object_key   = recordings/<tenant_id>/<yyyy>/<mm>/<dd>/<call_id>.dek.enc
	//
	// dek_object_key is OPTIONAL in v1 — encrypted_dek lives in-row in
	// call_recordings. The sidecar object is reserved for v2 client-side decryption.
	S3Bucket       string `protobuf:"bytes,3,opt,name=s3_bucket,json=s3Bucket,proto3" json:"s3_bucket,omitempty"`
	AudioObjectKey string `protobuf:"bytes,4,opt,name=audio_object_key,json=audioObjectKey,proto3" json:"audio_object_key,omitempty"`
	DekObjectKey   string `protobuf:"bytes,5,opt,name=dek_object_key,json=dekObjectKey,proto3" json:"dek_object_key,omitempty"` // may be empty in v1
	// Cryptographic envelope (per-recording DEK wrapped by per-tenant KMS KEK).
	KmsKeyId     string               `protobuf:"bytes,6,opt,name=kms_key_id,json=kmsKeyId,proto3" json:"kms_key_id,omitempty"`           // Yandex Cloud KMS key id
	EncryptedDek []byte               `protobuf:"bytes,7,opt,name=encrypted_dek,json=encryptedDek,proto3" json:"encrypted_dek,omitempty"` // ~88 bytes for KMS-wrapped 32-byte DEK; <= 4096 bytes
	BytesSize    int64                `protobuf:"varint,8,opt,name=bytes_size,json=bytesSize,proto3" json:"bytes_size,omitempty"`         // .opus.enc file size, > 0
	Duration     *durationpb.Duration `protobuf:"bytes,9,opt,name=duration,proto3" json:"duration,omitempty"`                             // > 0
	Sha256       string               `protobuf:"bytes,10,opt,name=sha256,proto3" json:"sha256,omitempty"`                                // hex, 64 chars, of CIPHERTEXT
	Codec        string               `protobuf:"bytes,11,opt,name=codec,proto3" json:"codec,omitempty"`                                  // "opus" or "opus-32"
	SampleRate   int32                `protobuf:"varint,12,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`     // 48000 typical, > 0
	// Retention plan — resolved by uploader from project policy + tenant defaults.
	DeleteAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=delete_at,json=deleteAt,proto3" json:"delete_at,omitempty"`
	ColdAt   *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=cold_at,json=coldAt,proto3" json:"cold_at,omitempty"`
	// Provenance.
	IngestAgentId string                 `protobuf:"bytes,15,opt,name=ingest_agent_id,json=ingestAgentId,proto3" json:"ingest_agent_id,omitempty"`
	RecordedAt    *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitRequest) Reset() {
	*x = CommitRequest{}
	mi := &file_recording_v1_recording_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitRequest) ProtoMessage() {}

func (x *CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recording_v1_recording_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitRequest.ProtoReflect.Descriptor instead.
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return file_recording_v1_recording_proto_rawDescGZIP(), []int{0}
}

func (x *CommitRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CommitRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CommitRequest) GetS3Bucket() string {
	if x != nil {
		return x.S3Bucket
	}
	return ""
}

func (x *CommitRequest) GetAudioObjectKey() string {
	if x != nil {
		return x.AudioObjectKey
	}
	return ""
}

func (x *CommitRequest) GetDekObjectKey() string {
	if x != nil {
		return x.DekObjectKey
	}
	return ""
}

func (x *CommitRequest) GetKmsKeyId() string {
	if x != nil {
		return x.KmsKeyId
	}
	return ""
}

func (x *CommitRequest) GetEncryptedDek() []byte {
	if x != nil {
		return x.EncryptedDek
	}
	return nil
}

func (x *CommitRequest) GetBytesSize() int64 {
	if x != nil {
		return x.BytesSize
	}
	return 0
}

func (x *CommitRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *CommitRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *CommitRequest) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *CommitRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *CommitRequest) GetDeleteAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteAt
	}
	return nil
}

func (x *CommitRequest) GetColdAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ColdAt
	}
	return nil
}

func (x *CommitRequest) GetIngestAgentId() string {
	if x != nil {
		return x.IngestAgentId
	}
	return ""
}

func (x *CommitRequest) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

type CommitResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecordingId      string                 `protobuf:"bytes,1,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	CallId           string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	CommittedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	IdempotentReplay bool                   `protobuf:"varint,4,opt,name=idempotent_replay,json=idempotentReplay,proto3" json:"idempotent_replay,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommitResponse) Reset() {
	*x = CommitResponse{}
	mi := &file_recording_v1_recording_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitResponse) ProtoMessage() {}

func (x *CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recording_v1_recording_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitResponse.ProtoReflect.Descriptor instead.
func (*CommitResponse) Descriptor() ([]byte, []int) {
	return file_recording_v1_recording_proto_rawDescGZIP(), []int{1}
}

func (x *CommitResponse) GetRecordingId() string {
	if x != nil {
		return x.RecordingId
	}
	return ""
}

func (x *CommitResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CommitResponse) GetCommittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CommittedAt
	}
	return nil
}

func (x *CommitResponse) GetIdempotentReplay() bool {
	if x != nil {
		return x.IdempotentReplay
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_recording_v1_recording_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recording_v1_recording_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_recording_v1_recording_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

type GetResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecordingId    string                 `protobuf:"bytes,1,opt,name=recording_id,json=recordingId,proto3" json:"recording_id,omitempty"`
	CallId         string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	S3Bucket       string                 `protobuf:"bytes,4,opt,name=s3_bucket,json=s3Bucket,proto3" json:"s3_bucket,omitempty"`
	AudioObjectKey string                 `protobuf:"bytes,5,opt,name=audio_object_key,json=audioObjectKey,proto3" json:"audio_object_key,omitempty"`
	BytesSize      int64                  `protobuf:"varint,6,opt,name=bytes_size,json=bytesSize,proto3" json:"bytes_size,omitempty"`
	Duration       *durationpb.Duration   `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Sha256         string                 `protobuf:"bytes,8,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CommittedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=committed_at,json=committedAt,proto3" json:"committed_at,omitempty"`
	DeleteAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=delete_at,json=deleteAt,proto3" json:"delete_at,omitempty"`
	ColdAt         *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=cold_at,json=coldAt,proto3" json:"cold_at,omitempty"`
	VerifiedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_recording_v1_recording_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recording_v1_recording_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_recording_v1_recording_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetRecordingId() string {
	if x != nil {
		return x.RecordingId
	}
	return ""
}

func (x *GetResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *GetResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetResponse) GetS3Bucket() string {
	if x != nil {
		return x.S3Bucket
	}
	return ""
}

func (x *GetResponse) GetAudioObjectKey() string {
	if x != nil {
		return x.AudioObjectKey
	}
	return ""
}

func (x *GetResponse) GetBytesSize() int64 {
	if x != nil {
		return x.BytesSize
	}
	return 0
}

func (x *GetResponse) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *GetResponse) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *GetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetResponse) GetCommittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CommittedAt
	}
	return nil
}

func (x *GetResponse) GetDeleteAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteAt
	}
	return nil
}

func (x *GetResponse) GetColdAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ColdAt
	}
	return nil
}

func (x *GetResponse) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

var File_recording_v1_recording_proto protoreflect.FileDescriptor

const file_recording_v1_recording_proto_rawDesc = "" +
	"\n" +
	"\x1crecording/v1/recording.proto\x12\x17sociopulse.recording.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xed\x04\n" +
	"\rCommitRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x1b\n" +
	"\ts3_bucket\x18\x03 \x01(\tR\bs3Bucket\x12(\n" +
	"\x10audio_object_key\x18\x04 \x01(\tR\x0eaudioObjectKey\x12$\n" +
	"\x0edek_object_key\x18\x05 \x01(\tR\fdekObjectKey\x12\x1c\n" +
	"\n" +
	"kms_key_id\x18\x06 \x01(\tR\bkmsKeyId\x12#\n" +
	"\rencrypted_dek\x18\a \x01(\fR\fencryptedDek\x12\x1d\n" +
	"\n" +
	"bytes_size\x18\b \x01(\x03R\tbytesSize\x125\n" +
	"\bduration\x18\t \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x16\n" +
	"\x06sha256\x18\n" +
	" \x01(\tR\x06sha256\x12\x14\n" +
	"\x05codec\x18\v \x01(\tR\x05codec\x12\x1f\n" +
	"\vsample_rate\x18\f \x01(\x05R\n" +
	"sampleRate\x127\n" +
	"\tdelete_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\bdeleteAt\x123\n" +
	"\acold_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\x06coldAt\x12&\n" +
	"\x0fingest_agent_id\x18\x0f \x01(\tR\ringestAgentId\x12;\n" +
	"\vrecorded_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\"\xb8\x01\n" +
	"\x0eCommitResponse\x12!\n" +
	"\frecording_id\x18\x01 \x01(\tR\vrecordingId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12=\n" +
	"\fcommitted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcommittedAt\x12+\n" +
	"\x11idempotent_replay\x18\x04 \x01(\bR\x10idempotentReplay\"B\n" +
	"\n" +
	"GetRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\"\x9d\x04\n" +
	"\vGetResponse\x12!\n" +
	"\frecording_id\x18\x01 \x01(\tR\vrecordingId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1b\n" +
	"\ts3_bucket\x18\x04 \x01(\tR\bs3Bucket\x12(\n" +
	"\x10audio_object_key\x18\x05 \x01(\tR\x0eaudioObjectKey\x12\x1d\n" +
	"\n" +
	"bytes_size\x18\x06 \x01(\x03R\tbytesSize\x125\n" +
	"\bduration\x18\a \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x16\n" +
	"\x06sha256\x18\b \x01(\tR\x06sha256\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12=\n" +
	"\fcommitted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcommittedAt\x127\n" +
	"\tdelete_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\bdeleteAt\x123\n" +
	"\acold_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x06coldAt\x12;\n" +
	"\vverified_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt2\xbf\x01\n" +
	"\x10RecordingService\x12Y\n" +
	"\x06Commit\x12&.sociopulse.recording.v1.CommitRequest\x1a'.sociopulse.recording.v1.CommitResponse\x12P\n" +
	"\x03Get\x12#.sociopulse.recording.v1.GetRequest\x1a$.sociopulse.recording.v1.GetResponseBHZFgithub.com/sociopulse/platform/internal/recording/proto/v1;recordingv1b\x06proto3"

var (
	file_recording_v1_recording_proto_rawDescOnce sync.Once
	file_recording_v1_recording_proto_rawDescData []byte
)

func file_recording_v1_recording_proto_rawDescGZIP() []byte {
	file_recording_v1_recording_proto_rawDescOnce.Do(func() {
		file_recording_v1_recording_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recording_v1_recording_proto_rawDesc), len(file_recording_v1_recording_proto_rawDesc)))
	})
	return file_recording_v1_recording_proto_rawDescData
}

var file_recording_v1_recording_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_recording_v1_recording_proto_goTypes = []any{
	(*CommitRequest)(nil),         // 0: sociopulse.recording.v1.CommitRequest
	(*CommitResponse)(nil),        // 1: sociopulse.recording.v1.CommitResponse
	(*GetRequest)(nil),            // 2: sociopulse.recording.v1.GetRequest
	(*GetResponse)(nil),           // 3: sociopulse.recording.v1.GetResponse
	(*durationpb.Duration)(nil),   // 4: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_recording_v1_recording_proto_depIdxs = []int32{
	4,  // 0: sociopulse.recording.v1.CommitRequest.duration:type_name -> google.protobuf.Duration
	5,  // 1: sociopulse.recording.v1.CommitRequest.delete_at:type_name -> google.protobuf.Timestamp
	5,  // 2: sociopulse.recording.v1.CommitRequest.cold_at:type_name -> google.protobuf.Timestamp
	5,  // 3: sociopulse.recording.v1.CommitRequest.recorded_at:type_name -> google.protobuf.Timestamp
	5,  // 4: sociopulse.recording.v1.CommitResponse.committed_at:type_name -> google.protobuf.Timestamp
	4,  // 5: sociopulse.recording.v1.GetResponse.duration:type_name -> google.protobuf.Duration
	5,  // 6: sociopulse.recording.v1.GetResponse.committed_at:type_name -> google.protobuf.Timestamp
	5,  // 7: sociopulse.recording.v1.GetResponse.delete_at:type_name -> google.protobuf.Timestamp
	5,  // 8: sociopulse.recording.v1.GetResponse.cold_at:type_name -> google.protobuf.Timestamp
	5,  // 9: sociopulse.recording.v1.GetResponse.verified_at:type_name -> google.protobuf.Timestamp
	0,  // 10: sociopulse.recording.v1.RecordingService.Commit:input_type -> sociopulse.recording.v1.CommitRequest
	2,  // 11: sociopulse.recording.v1.RecordingService.Get:input_type -> sociopulse.recording.v1.GetRequest
	1,  // 12: sociopulse.recording.v1.RecordingService.Commit:output_type -> sociopulse.recording.v1.CommitResponse
	3,  // 13: sociopulse.recording.v1.RecordingService.Get:output_type -> sociopulse.recording.v1.GetResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_recording_v1_recording_proto_init() }
func file_recording_v1_recording_proto_init() {
	if File_recording_v1_recording_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recording_v1_recording_proto_rawDesc), len(file_recording_v1_recording_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recording_v1_recording_proto_goTypes,
		DependencyIndexes: file_recording_v1_recording_proto_depIdxs,
		MessageInfos:      file_recording_v1_recording_proto_msgTypes,
	}.Build()
	File_recording_v1_recording_proto = out.File
	file_recording_v1_recording_proto_goTypes = nil
	file_recording_v1_recording_proto_depIdxs = nil
}
