// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.1
// source: recording/v1/recording.proto

package recordingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecordingService_Commit_FullMethodName = "/sociopulse.recording.v1.RecordingService/Commit"
	RecordingService_Get_FullMethodName    = "/sociopulse.recording.v1.RecordingService/Get"
)

// RecordingServiceClient is the client API for RecordingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RecordingService — internal gRPC API consumed by cmd/recording-uploader (out
// of scope for Plan 12.1 — that command lives in Plan 08 or a future plan).
// Mounted on :9091 alongside cmd/api's HTTP listener. mTLS is REQUIRED — the
// server interceptor extracts a SPIFFE-style identity from the verified client
// cert.
type RecordingServiceClient interface {
	// Commit registers a recording that the uploader has already streamed to S3
	// (.opus.enc) along with its envelope-wrapped DEK (encrypted_dek bytes;
	// sidecar .dek.enc S3 object is reserved for v2).
	//
	// Idempotency: keyed by call_id (UNIQUE constraint in call_recordings).
	// A duplicate Commit for the same call_id returns the EXISTING row's
	// metadata with idempotent_replay=true.
	//
	// Errors:
	//
	//	INVALID_ARGUMENT — sha256 length != 64 hex chars, bytes_size <= 0,
	//	                   missing required field.
	//	FAILED_PRECONDITION — call_id has no matching row in calls(id, tenant_id).
	//	PERMISSION_DENIED — request.tenant_id mismatches the SPIFFE tenant in the
	//	                    client cert.
	//	UNAUTHENTICATED — peer cert chain missing / invalid / no SPIFFE URI SAN.
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	// Get returns metadata for a single recording (NO audio bytes — public reads
	// go via HTTP). Used for health-check, diagnostics, and future
	// cmd/recording-uploader retry handshakes.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type recordingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordingServiceClient(cc grpc.ClientConnInterface) RecordingServiceClient {
	return &recordingServiceClient{cc}
}

func (c *recordingServiceClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, RecordingService_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordingServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, RecordingService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordingServiceServer is the server API for RecordingService service.
// All implementations must embed UnimplementedRecordingServiceServer
// for forward compatibility.
//
// RecordingService — internal gRPC API consumed by cmd/recording-uploader (out
// of scope for Plan 12.1 — that command lives in Plan 08 or a future plan).
// Mounted on :9091 alongside cmd/api's HTTP listener. mTLS is REQUIRED — the
// server interceptor extracts a SPIFFE-style identity from the verified client
// cert.
type RecordingServiceServer interface {
	// Commit registers a recording that the uploader has already streamed to S3
	// (.opus.enc) along with its envelope-wrapped DEK (encrypted_dek bytes;
	// sidecar .dek.enc S3 object is reserved for v2).
	//
	// Idempotency: keyed by call_id (UNIQUE constraint in call_recordings).
	// A duplicate Commit for the same call_id returns the EXISTING row's
	// metadata with idempotent_replay=true.
	//
	// Errors:
	//
	//	INVALID_ARGUMENT — sha256 length != 64 hex chars, bytes_size <= 0,
	//	                   missing required field.
	//	FAILED_PRECONDITION — call_id has no matching row in calls(id, tenant_id).
	//	PERMISSION_DENIED — request.tenant_id mismatches the SPIFFE tenant in the
	//	                    client cert.
	//	UNAUTHENTICATED — peer cert chain missing / invalid / no SPIFFE URI SAN.
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	// Get returns metadata for a single recording (NO audio bytes — public reads
	// go via HTTP). Used for health-check, diagnostics, and future
	// cmd/recording-uploader retry handshakes.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedRecordingServiceServer()
}

// UnimplementedRecordingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordingServiceServer struct{}

func (UnimplementedRecordingServiceServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedRecordingServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRecordingServiceServer) mustEmbedUnimplementedRecordingServiceServer() {}
func (UnimplementedRecordingServiceServer) testEmbeddedByValue()                          {}

// UnsafeRecordingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordingServiceServer will
// result in compilation errors.
type UnsafeRecordingServiceServer interface {
	mustEmbedUnimplementedRecordingServiceServer()
}

func RegisterRecordingServiceServer(s grpc.ServiceRegistrar, srv RecordingServiceServer) {
	// If the following call panics, it indicates UnimplementedRecordingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordingService_ServiceDesc, srv)
}

func _RecordingService_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingServiceServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordingService_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingServiceServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordingService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordingServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordingService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordingServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordingService_ServiceDesc is the grpc.ServiceDesc for RecordingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sociopulse.recording.v1.RecordingService",
	HandlerType: (*RecordingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Commit",
			Handler:    _RecordingService_Commit_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RecordingService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recording/v1/recording.proto",
}
