// Package api defines public contracts for the crm module.
// Other modules import only from this package — never from crm/service or crm/store.
//
// crm owns project lifecycle, respondents, quotas, DNC, async CSV/XLSX import,
// the 152-ФЗ deletion right (30-day soft-delete + worker purge), Russian phone
// validation/normalization (E.164 + АВС/DEF prefix mapping), and the
// real-time quota tracker with Redis cache and Postgres reconciliation worker.
package api

import (
	"time"

	"github.com/google/uuid"
)

// ProjectStatus enumerates the lifecycle states of a Project.
type ProjectStatus string

const (
	StatusActive   ProjectStatus = "active"
	StatusPaused   ProjectStatus = "paused"
	StatusArchived ProjectStatus = "archived"
)

// Project is the public projection of a project row.
type Project struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	Code                   string
	Name                   string
	Customer               string
	Status                 ProjectStatus
	TargetCount            int
	PeriodFrom             *time.Time
	PeriodTo               *time.Time
	SurveyID               *uuid.UUID
	DefaultSurveyVersionID *uuid.UUID
	IsAdvertising          bool
	CreatedBy              *uuid.UUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
	ArchivedAt             *time.Time
	Quotas                 []Quota
	Assignments            []ProjectMember
}

// CreateProjectInput is the payload for ProjectService.Create.
type CreateProjectInput struct {
	TenantID       uuid.UUID
	Code           string
	Name           string
	Customer       string
	TargetCount    int
	PeriodFrom     *time.Time
	PeriodTo       *time.Time
	SurveyID       *uuid.UUID
	IsAdvertising  bool
	InitialQuotas  []Quota
	InitialMembers []uuid.UUID
}

// UpdateProjectInput carries the patch fields for ProjectService.Update.
// Pointer-typed fields denote optional patches: nil means "leave unchanged".
type UpdateProjectInput struct {
	Name        *string
	Customer    *string
	TargetCount *int
	PeriodFrom  *time.Time
	PeriodTo    *time.Time
	SurveyID    *uuid.UUID
}

// ProjectMember describes one operator assignment to a project. Login
// and FullName are populated by ListMembers (joined from users) for
// display purposes; they remain zero-valued when the entry is built
// from a write path that doesn't touch users.
type ProjectMember struct {
	OperatorID uuid.UUID
	AssignedAt time.Time
	Login      string
	FullName   string
}

// ListProjectsFilter narrows ProjectService.List.
//
// Limit/Offset are the canonical pagination knobs the service layer clamps
// to [1, 500] / >=0 (defaults: Limit=50, Offset=0). IncludeArchived defaults
// to false so admin lists hide soft-deleted rows; passing true surfaces them
// for a "show all" view. Status/Search remain optional narrow filters.
type ListProjectsFilter struct {
	TenantID        uuid.UUID
	Status          *ProjectStatus
	Search          string
	IncludeArchived bool
	Limit           int
	Offset          int
}

// ListProjectsResult is the page-with-total response for ProjectService.List.
type ListProjectsResult struct {
	Items      []Project
	TotalCount int64
}

// ProjectProgress is the live counter snapshot used by the dashboard
// "project progress" widget.
type ProjectProgress struct {
	ProjectID       uuid.UUID
	TargetCount     int
	CompletedCount  int
	InProgressCount int
	PendingCount    int
	DNCCount        int
	ExhaustedCount  int
	WrongCount      int
	PercentDone     float64
	PaceLast24h     int
	ETACompletion   *time.Time
	QuotaProgress   []QuotaSnapshot
}

// Quota is one row in a project's quota plan.
type Quota struct {
	DimensionKind  string // "region" | "gender" | "age_bucket" | "custom"
	DimensionValue string
	Target         int
}

// QuotaSnapshot is the realtime tracker's view of one quota cell.
type QuotaSnapshot struct {
	DimensionKind  string
	DimensionValue string
	Target         int
	Done           int
	PercentDone    float64
	IsFull         bool
}

// RespondentStatus enumerates the lifecycle states of a Respondent.
type RespondentStatus string

const (
	RespPending           RespondentStatus = "pending"
	RespDialing           RespondentStatus = "dialing"
	RespCompleted         RespondentStatus = "completed"
	RespDNC               RespondentStatus = "dnc"
	RespExhausted         RespondentStatus = "exhausted"
	RespWrong             RespondentStatus = "wrong"
	RespDeletionRequested RespondentStatus = "deletion-requested"
)

// RespondentSource enumerates the row's provenance — operators can see
// "imported" rows (CSV/XLSX uploads) and "rdd" rows (Random Digit
// Dialling, autogenerated). The two values match the CHECK constraint
// on respondents.source declared in 000001_init.up.sql.
const (
	// SourceImported marks rows that originated from an operator
	// CSV/XLSX import. The vast majority of v1 traffic.
	SourceImported = "imported"
	// SourceRDD marks rows that were synthesised by the Random Digit
	// Dialling generator. Reserved for future tasks; included here so
	// the constant block is exhaustive.
	SourceRDD = "rdd"
)

// Respondent is the public projection of a respondent row.
//
// Phone is populated only by GetWithPhone (admin-only); PhoneMasked is the
// display-safe variant returned to operators (e.g. "+7-9** ***-**-12").
//
// PhoneEncrypted / PhoneHash are the at-rest representation. The store
// reads/writes them as bytea; the service layer never decrypts inside
// Create/Get, only inside the explicit GetWithPhone path. Both fields
// are exposed here (rather than hidden in the store-layer DTO) so
// internal/crm/service can build/insert respondents without crossing
// the depguard module-boundaries rule that would otherwise force the
// service to import the store package.
type Respondent struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	ProjectID      uuid.UUID
	PhoneMasked    string
	Phone          string
	PhoneEncrypted []byte
	PhoneHash      []byte
	RegionCode     string
	Attributes     map[string]any
	Status         RespondentStatus
	Attempts       int
	LastAttemptAt  *time.Time
	NextAttemptAt  *time.Time
	Source         string // SourceImported | SourceRDD
	CreatedAt      time.Time
	DeleteAt       *time.Time
}

// CreateRespondentInput is the payload for RespondentService.Create.
//
// TenantID is mandatory: callers MUST pass the tenant explicitly so the
// service writes through the correct tenant tx (Pool.WithTenant). The
// HTTP transport derives it from the JWT claims.
//
// Source is optional — service defaults to SourceImported when blank
// (single-add via UI is functionally an import-of-one).
type CreateRespondentInput struct {
	TenantID   uuid.UUID
	ProjectID  uuid.UUID
	Phone      string
	RegionCode string
	Attributes map[string]any
	Source     string
}

// SearchRespondentsFilter narrows RespondentService.Search.
//
// TenantID is mandatory for the store layer (RLS still scopes the
// query, but the explicit predicate makes the query plan cheaper); the
// HTTP transport derives it from the JWT claims.
//
// PhoneSearch is matched against the masked phone-suffix column (when
// the project gains one) — for v1 we restrict the search to project +
// status + region filters, plus an optional Query token that runs
// against the JSON attributes blob (full_name / external_ref columns
// when present). Wide-open phone-prefix search is INTENTIONALLY not
// supported: phone_hash is the only at-rest representation, and
// hashing is not reversible. Future tasks may add a separate
// phone-suffix index, but for v1 operators who need a phone-based
// lookup use Get / GetWithPhone with a known id.
type SearchRespondentsFilter struct {
	TenantID    uuid.UUID
	ProjectID   uuid.UUID
	Status      *RespondentStatus
	PhoneSearch string
	Region      string
	Query       string
	Page        int
	PageSize    int
}

// SearchRespondentsResult is the page-with-total response for RespondentService.Search.
type SearchRespondentsResult struct {
	Items      []Respondent
	TotalCount int
}

// ImportFormat enumerates the file formats accepted by Import.
type ImportFormat string

const (
	// ImportFormatCSV is text/csv (RFC 4180-ish; we strip BOM, accept
	// CRLF line endings, and tolerate NBSP / em-dash inside phone cells).
	ImportFormatCSV ImportFormat = "csv"
	// ImportFormatXLSX is the Office Open XML spreadsheet format read
	// via the streaming excelize iterator.
	ImportFormatXLSX ImportFormat = "xlsx"
)

// ImportRequest is the payload for RespondentService.Import.
//
// JobID is optional at the API surface — the service mints a UUIDv7
// when blank and returns the assigned id in the ticket. Callers that
// implement client-side retry should mint and pass the same JobID
// across retries; asynq's Unique option ensures the second enqueue is
// dropped (ErrDuplicateTask) so a flaky network does not double-import.
//
// TenantID is mandatory and MUST be derived from the caller's JWT
// claims by the HTTP transport (Plan 06 Task 5). The service rejects
// uuid.Nil with ErrInvalidArgument.
//
// Body is the raw file bytes; for v1 we accept payload-inline so
// integration tests don't need an S3 backend. Plan 12 swaps this for a
// blob_key reference when S3 is wired.
type ImportRequest struct {
	JobID        string
	TenantID     uuid.UUID
	ProjectID    uuid.UUID
	Format       ImportFormat
	Source       string
	Filename     string
	ContentType  string
	Body         []byte
	ColumnMap    map[string]string
	DefaultAttrs map[string]any
}

// ImportTicket is returned synchronously when an import is accepted; the
// real result is observed via the asynq task and the import.* events.
type ImportTicket struct {
	JobID     string
	ProjectID uuid.UUID
	Enqueued  bool
	Status    string
	Total     int
	StartedAt time.Time
}

// ImportStatus is the polling response for RespondentService.GetImportStatus.
type ImportStatus struct {
	JobID      string
	State      string // "queued" | "running" | "succeeded" | "failed"
	Total      int
	Processed  int
	Inserted   int
	Skipped    int
	Errors     []ImportError
	StartedAt  time.Time
	FinishedAt *time.Time
}

// ImportError is one row-level error from an import job.
type ImportError struct {
	Row     int
	Phone   string
	Message string
}

// DeletionRequest is the receipt returned from RespondentService.Delete.
// The respondent transitions to RespDeletionRequested and is purged after
// 30 days by the cmd/worker purge task (152-ФЗ §13.3).
type DeletionRequest struct {
	RespondentID uuid.UUID
	DeleteAt     time.Time
}

// DNCEntry is one row in the do-not-call list. PhoneMasked is the
// display-safe variant; the raw phone is never returned by the API.
type DNCEntry struct {
	PhoneMasked string
	Source      string
	AddedAt     int64
}
