package store

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"sync"

	"github.com/google/uuid"

	"github.com/sociopulse/platform/internal/tenancy/api"
	"github.com/sociopulse/platform/pkg/encryption"
)

// localKMSClient is the in-process AES-256-GCM fallback used by the dev
// stack (`make dev-up`) when no real Yandex KMS endpoint is configured.
//
// Design notes:
//   - Each "KEK" is a 32-byte symmetric key generated by crypto/rand on
//     CreateKey. The master hex key passed to NewLocalKMSClient is mixed
//     into a per-key HKDF-style derivation so two processes seeded with
//     the same hex string produce stable derived KEKs across restarts of
//     the same tenant catalog.
//   - DEKs are wrapped by AES-256-GCM with the KEK, prefixed with the
//     KEK's 16-byte fingerprint so Decrypt can reject ciphertext that was
//     produced by a different key.
//   - Keys live only in memory: this implementation is for dev/test only
//     and is NOT suitable for production. Process restart drops every key.
//
// Compile-time check: implements api.KMSClient.
type localKMSClient struct {
	masterKey []byte // 32 bytes; mixed into per-tenant key derivation

	mu   sync.RWMutex
	keys map[string][]byte // keyID -> 32-byte derived KEK
}

// kekFingerprintLen is the number of bytes of SHA-256(KEK) that we prepend
// to every ciphertext. Long enough to make collisions astronomically rare,
// short enough to keep the wrapped DEK compact.
const kekFingerprintLen = 16

// localKEKVersion is the version string returned by Encrypt/Decrypt. The
// local implementation has no rotation; the value is fixed so callers can
// rely on it being non-empty.
const localKEKVersion = "local-v1"

// NewLocalKMSClient builds an in-process KMSClient suitable for dev and
// integration tests.
//
// masterKeyHex is a 32-byte (64-hex-char) random string that seeds the
// per-tenant KEK derivation. In dev YAML it lives under
// `kms.local_key_hex`; in tests, the caller passes a freshly generated
// value via genHexKey(t).
func NewLocalKMSClient(masterKeyHex string) (api.KMSClient, error) {
	if masterKeyHex == "" {
		return nil, errors.New("local kms: master key hex is required")
	}
	master, err := hex.DecodeString(masterKeyHex)
	if err != nil {
		return nil, fmt.Errorf("local kms: decode master key hex: %w", err)
	}
	if len(master) != encryption.KeyLen {
		return nil, fmt.Errorf("local kms: master key must be %d bytes (got %d)",
			encryption.KeyLen, len(master))
	}
	return &localKMSClient{
		masterKey: master,
		keys:      make(map[string][]byte),
	}, nil
}

// CreateKey allocates a fresh per-tenant KEK and returns its identifier.
// The key material is derived from masterKey + a per-call random salt so
// every CreateKey invocation produces a distinct KEK.
func (c *localKMSClient) CreateKey(_ context.Context, name, _ string) (string, error) {
	salt := make([]byte, 16)
	if _, err := rand.Read(salt); err != nil {
		return "", fmt.Errorf("local kms: read salt: %w", err)
	}

	// Derive a 32-byte KEK = SHA-256(masterKey || name || salt).
	// HKDF-Extract level of mixing — sufficient for a dev fallback. The
	// real Yandex client never sees masterKey.
	h := sha256.New()
	h.Write(c.masterKey)
	h.Write([]byte(name))
	h.Write(salt)
	kek := h.Sum(nil) // 32 bytes; matches encryption.KeyLen

	keyID := "local-" + uuid.NewString()

	c.mu.Lock()
	c.keys[keyID] = kek
	c.mu.Unlock()
	return keyID, nil
}

// Encrypt wraps plaintext with the named KEK and returns
// fingerprint(16) || nonce(12) || aes-gcm-body. The fingerprint lets
// Decrypt reject ciphertext produced by a different KEK before it ever
// reaches GCM.
func (c *localKMSClient) Encrypt(_ context.Context, keyID string, plaintext []byte) ([]byte, string, error) {
	kek, ok := c.lookup(keyID)
	if !ok {
		return nil, "", fmt.Errorf("%w: keyID=%q", api.ErrKEKNotFound, keyID)
	}
	body, err := encryption.Encrypt(kek, plaintext, nil)
	if err != nil {
		return nil, "", fmt.Errorf("local kms: encrypt: %w", err)
	}
	fp := fingerprint(kek)
	out := make([]byte, 0, kekFingerprintLen+len(body))
	out = append(out, fp...)
	out = append(out, body...)
	return out, localKEKVersion, nil
}

// Decrypt unwraps a ciphertext that was produced by Encrypt with the same
// KEK. Returns api.ErrKEKNotFound if the keyID is unknown, or
// api.ErrInvalidWrappedDEK if the fingerprint mismatches the named key.
func (c *localKMSClient) Decrypt(_ context.Context, keyID string, ciphertext []byte) ([]byte, string, error) {
	kek, ok := c.lookup(keyID)
	if !ok {
		return nil, "", fmt.Errorf("%w: keyID=%q", api.ErrKEKNotFound, keyID)
	}
	if len(ciphertext) < kekFingerprintLen {
		return nil, "", fmt.Errorf("%w: ciphertext too short", api.ErrInvalidWrappedDEK)
	}
	gotFP := ciphertext[:kekFingerprintLen]
	body := ciphertext[kekFingerprintLen:]
	if !bytesEqualConstantTime(gotFP, fingerprint(kek)) {
		return nil, "", fmt.Errorf("%w: fingerprint mismatch", api.ErrInvalidWrappedDEK)
	}
	pt, err := encryption.Decrypt(kek, body, nil)
	if err != nil {
		// pkg/encryption already wraps GCM failures as ErrAuth — relabel as
		// invalid-wrapped-DEK so callers can distinguish "tampering / wrong
		// key" from "KMS down".
		return nil, "", fmt.Errorf("%w: %w", api.ErrInvalidWrappedDEK, err)
	}
	return pt, localKEKVersion, nil
}

// GenerateDataKey produces a fresh 32-byte plaintext DEK and returns it
// alongside its KEK-wrapped ciphertext. Mirrors Yandex KMS semantics:
// the caller MAY use the plaintext for a single envelope encryption op
// and MUST persist the ciphertext.
func (c *localKMSClient) GenerateDataKey(ctx context.Context, keyID string) ([]byte, []byte, string, error) {
	dek := make([]byte, encryption.KeyLen)
	if _, err := rand.Read(dek); err != nil {
		return nil, nil, "", fmt.Errorf("local kms: generate dek: %w", err)
	}
	wrapped, ver, err := c.Encrypt(ctx, keyID, dek)
	if err != nil {
		return nil, nil, "", err
	}
	return dek, wrapped, ver, nil
}

func (c *localKMSClient) lookup(keyID string) ([]byte, bool) {
	c.mu.RLock()
	defer c.mu.RUnlock()
	kek, ok := c.keys[keyID]
	return kek, ok
}

// fingerprint returns the first kekFingerprintLen bytes of SHA-256(kek).
// Used as a non-cryptographic equality probe — the real authentication of
// the ciphertext is GCM's tag, this is just a fast-fail hint.
func fingerprint(kek []byte) []byte {
	sum := sha256.Sum256(kek)
	return sum[:kekFingerprintLen]
}

// bytesEqualConstantTime is crypto/subtle.ConstantTimeCompare adapted to
// our return shape. We use it for the fingerprint check so a timing-aware
// attacker cannot probe KEK material via decrypt latency.
func bytesEqualConstantTime(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	var diff byte
	for i := range a {
		diff |= a[i] ^ b[i]
	}
	return diff == 0
}
